import './globals.css'
import { home } from '@/data/home'
import { Navigation } from '@/components/navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <header className="bg-white">
          <Navigation navLinks={home} />
        </header>
        <div className="overflow-auto">{children}</div>
      </body>
    </html>
  )
}
