import 'antd-mobile/es/global'
import './globals.css'
import { FooterBar } from '@/components/footerBar'

import { Providers } from '@/store/providers'

export const metadata = {
  title: 'React Next App',
  description: 'Generated by create next app',
  viewport: {
    viewportFit: 'cover',
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className="flex flex-col">
          <div className="overflow-auto flex-1">{children}</div>
          <FooterBar />
        </body>
      </html>
    </Providers>
  )
}
